export interface Job {
  id: string
  title: string
  company: string
  location: string
  type: string
  hoursPerWeek: number
  workDays: string
  description: string
  datePosted: string
  aboutUs: string
  opportunity: string
  requirements: string[]
  benefits: string[]
  expirationDate: string
  workType: 'onsite' | 'hybrid' | 'remote'
}

export const jobList: Job[] = [
  {
    id: '1',
    title: 'Software Developer',
    company: 'TechCorp',
    location: 'New York, NY',
    type: 'Full-time',
    hoursPerWeek: 40,
    workDays: 'Monday to Friday',
    description: 'Develop and maintain software applications.',
    datePosted: '2024-07-22',
    aboutUs: 'TechCorp is a leading software development company.',
    opportunity: 'This is a unique opportunity to grow your career.',
    requirements: [
      '3+ years of experience in software development',
      'Proficiency in JavaScript',
    ],
    benefits: ['Health insurance', '401(k)'],
    expirationDate: '2024-08-22',
    workType: 'onsite',
  },
  {
    id: '2',
    title: 'Product Manager',
    company: 'Innovate Ltd',
    location: 'San Francisco, CA',
    type: 'Full-Time',
    hoursPerWeek: 40,
    workDays: 'Monday to Friday',
    datePosted: '2024-07-15',
    expirationDate: '2024-09-15',
    description:
      'Lead the product development team in delivering high-quality products.',
    aboutUs: 'Innovate Ltd focuses on product innovation...',
    opportunity: 'Manage a diverse team of professionals...',
    requirements: [
      '5+ years in product management',
      'Excellent leadership skills',
    ],
    benefits: ['Stock options', 'Flexible working hours'],
    workType: 'hybrid',
  },
  {
    id: '3',
    title: 'UX Designer',
    company: 'DesignPro',
    location: 'Austin, TX',
    type: 'Part-Time',
    hoursPerWeek: 20,
    workDays: 'Monday, Wednesday, Friday',
    datePosted: '2024-06-20',
    expirationDate: '2024-07-20',
    description: 'Create user-centric designs for various applications.',
    aboutUs: 'DesignPro specializes in user experience design...',
    opportunity: 'Work on exciting new projects with a creative team...',
    requirements: ['Experience with wireframing tools', 'Portfolio required'],
    benefits: ['Remote work options', 'Professional development'],
    workType: 'hybrid',
  },
  {
    id: '4',
    title: 'Marketing Specialist',
    company: 'MarketMasters',
    location: 'Seattle, WA',
    type: 'Contract',
    hoursPerWeek: 30,
    workDays: 'Monday to Thursday',
    datePosted: '2024-08-01',
    expirationDate: '2024-12-01',
    description:
      'Develop and execute marketing campaigns to boost brand awareness.',
    aboutUs: 'MarketMasters is a leader in marketing solutions...',
    opportunity: 'Join a dynamic team and drive marketing success...',
    requirements: [
      'Experience in digital marketing',
      'Strong analytical skills',
    ],
    benefits: ['Health benefits', 'Paid leave'],
    workType: 'remote',
  },
  {
    id: '5',
    title: 'Data Analyst',
    company: 'DataGen',
    location: 'Chicago, IL',
    type: 'Full-Time',
    hoursPerWeek: 40,
    workDays: 'Monday to Friday',
    datePosted: '2024-07-10',
    expirationDate: '2024-08-10',
    description:
      'Analyze data and generate actionable insights for the company.',
    aboutUs: 'DataGen provides data-driven solutions...',
    opportunity: 'Be at the forefront of data analysis and strategy...',
    requirements: [
      'Proficiency in SQL and Python',
      'Strong problem-solving skills',
    ],
    benefits: ['Retirement plan', 'Annual bonuses'],
    workType: 'remote',
  },
  {
    id: '6',
    title: 'Sales Associate',
    company: 'RetailHub',
    location: 'Miami, FL',
    type: 'Part-Time',
    hoursPerWeek: 25,
    workDays: 'Tuesday to Saturday',
    datePosted: '2024-05-25',
    expirationDate: '2024-07-25',
    description: 'Assist customers and drive sales in a retail environment.',
    aboutUs: 'RetailHub is a leading retail store...',
    opportunity: 'Work in a fast-paced and rewarding environment...',
    requirements: ['Customer service experience', 'Good communication skills'],
    benefits: ['Employee discounts', 'Flexible shifts'],
    workType: 'onsite',
  },
  {
    id: '7',
    title: 'Graphic Designer',
    company: 'CreativeWorks',
    location: 'Boston, MA',
    type: 'Freelance',
    hoursPerWeek: 15,
    workDays: 'Flexible',
    datePosted: '2024-06-30',
    expirationDate: '2024-09-30',
    description: 'Design visual content for various clients and projects.',
    aboutUs: 'CreativeWorks provides creative design services...',
    opportunity:
      'Great opportunity for freelance work with diverse projects...',
    requirements: ['Strong portfolio', 'Experience with Adobe Creative Suite'],
    benefits: ['Flexible work schedule', 'Creative freedom'],
    workType: 'hybrid',
  },
  {
    id: '8',
    title: 'Web Developer',
    company: 'TechieHub',
    location: 'Denver, CO',
    type: 'Full-Time',
    hoursPerWeek: 40,
    workDays: 'Monday to Friday',
    datePosted: '2024-08-05',
    expirationDate: '2024-11-05',
    description: 'Build and maintain web applications for our clients.',
    aboutUs: 'TechieHub is a growing tech company...',
    opportunity: 'Work with cutting-edge technologies and a talented team...',
    requirements: ['Experience with React and Node.js', 'Strong coding skills'],
    benefits: ['Paid time off', 'Health insurance'],
    workType: 'hybrid',
  },
  {
    id: '9',
    title: 'Operations Manager',
    company: 'OpsMaster',
    location: 'San Diego, CA',
    type: 'Full-Time',
    hoursPerWeek: 40,
    workDays: 'Monday to Friday',
    datePosted: '2024-07-18',
    expirationDate: '2024-10-18',
    description: 'Manage day-to-day operations and ensure efficiency.',
    aboutUs: 'OpsMaster excels in operational excellence...',
    opportunity: 'Lead operations and drive process improvements...',
    requirements: ['Management experience', 'Strong organizational skills'],
    benefits: ['Performance bonuses', 'Retirement plan'],
    workType: 'onsite',
  },
  {
    id: '10',
    title: 'Customer Support Specialist',
    company: 'SupportPro',
    location: 'Atlanta, GA',
    type: 'Full-Time',
    hoursPerWeek: 40,
    workDays: 'Monday to Friday',
    datePosted: '2024-06-01',
    expirationDate: '2024-08-01',
    description: 'Provide exceptional support to customers and resolve issues.',
    aboutUs: 'SupportPro is dedicated to top-notch customer service...',
    opportunity: 'Join our support team and make a difference...',
    requirements: [
      'Excellent communication skills',
      'Experience in customer service',
    ],
    benefits: ['Health insurance', 'Paid time off'],
    workType: 'remote',
  },
  {
    id: '11',
    title: 'Content Writer',
    company: 'ContentCreators',
    location: 'Remote',
    type: 'Part-Time',
    hoursPerWeek: 20,
    workDays: 'Flexible',
    datePosted: '2024-08-10',
    expirationDate: '2024-12-10',
    description: 'Write and edit content for various platforms and clients.',
    aboutUs: 'ContentCreators provides high-quality content solutions...',
    opportunity: 'Work with diverse topics and clients...',
    requirements: ['Strong writing skills', 'Experience in content creation'],
    benefits: ['Flexible schedule', 'Creative projects'],
    workType: 'remote',
  },
  {
    id: '12',
    title: 'Network Engineer',
    company: 'NetworkPros',
    location: 'Philadelphia, PA',
    type: 'Full-Time',
    hoursPerWeek: 40,
    workDays: 'Monday to Friday',
    datePosted: '2024-07-25',
    expirationDate: '2024-09-25',
    description: 'Design and maintain network infrastructure for our clients.',
    aboutUs: 'NetworkPros specializes in networking solutions...',
    opportunity: 'Join our team and work on exciting network projects...',
    requirements: ['Experience with network protocols', 'CCNA certification'],
    benefits: ['Health benefits', 'Career development'],
    workType: 'onsite',
  },
  // Add more jobs here...
]
